source "https://github.com/itdongqiang/KAKASpec.git"

use_frameworks!

platform :ios, '9.0'

target 'KAKATools_Example' do
  pod 'KAKATools', :path => '../'

  target 'KAKATools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
